### PR TITLE
UAMS Client ID detector

### PR DESCRIPTION
**Pull request by raphael-theriault-swi**
Based on the oboe implementation

### CODE REVIEW

**Review by cheempz — COMMENTED** [review]
I'm reading the "[spec](https://github.com/solarwinds-cloud/trace/blob/master/docs/Collector-RPC-API.md#uamsclientid)" and we'll need two more things, one is a big question mark:
* easy: prefer the ID read from file
* ???: is it possible to update this attribute value every 60 seconds. the rationale is that the UAMS client aka SWO Host Agent may be installed/uninstalled after the instrumented application startup, and ideally we can reflect that for accurate host entity inference.

**Comment by cheempz** [comment]
I grimace because per current OTel spec, [resource attributes](https://opentelemetry.io/docs/specs/otel/resource/sdk/) are immutable once set on process startup. It's one of the problems the new [entity extension of resource attributes](https://github.com/open-telemetry/community/blob/main/projects/resources-and-entities.md) is meant to solve, but not sure how far along that is in implementation.

**Comment by raphael-theriault-swi** [comment]
Updating the attributes at runtime is either going to be extremely hard or impossible.

**Review by cheempz — APPROVED** [review]
LGTM, thanks @raphael-theriault-swi! To recap, decision is no refresh of this attribute as a known gap, to be addressed once upstream entities SDK can be used.

**Pull request merged**
